// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAreas(arg1:boolean):Promise<Array<string>>;

export function GetCountry(arg1:string):Promise<main.Country>;

export function GetCountryNames():Promise<Array<string>>;

export function GetDensities(arg1:boolean):Promise<Array<string>>;

export function GetPopulations(arg1:boolean):Promise<Array<string>>;
