// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAreas(arg1) {
  return window['go']['main']['App']['GetAreas'](arg1);
}

export function GetCountry(arg1) {
  return window['go']['main']['App']['GetCountry'](arg1);
}

export function GetCountryNames() {
  return window['go']['main']['App']['GetCountryNames']();
}

export function GetDensities(arg1) {
  return window['go']['main']['App']['GetDensities'](arg1);
}

export function GetPopulations(arg1) {
  return window['go']['main']['App']['GetPopulations'](arg1);
}
