// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCountryCode(arg1:string):Promise<string>;

export function GetCountryNames():Promise<Array<string>>;

export function GetRGDP(arg1:string):Promise<Array<main.Rgdp>>;

export function OneCountryLineChart(arg1:string,arg2:string):Promise<string>;

export function OpenLineChart(arg1:string,arg2:string):void;
