// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCountryCode(arg1) {
  return window['go']['main']['App']['GetCountryCode'](arg1);
}

export function GetCountryNames() {
  return window['go']['main']['App']['GetCountryNames']();
}

export function GetRGDP(arg1) {
  return window['go']['main']['App']['GetRGDP'](arg1);
}

export function OneCountryLineChart(arg1, arg2) {
  return window['go']['main']['App']['OneCountryLineChart'](arg1, arg2);
}

export function OpenLineChart(arg1, arg2) {
  return window['go']['main']['App']['OpenLineChart'](arg1, arg2);
}
