// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetData(arg1:string,arg2:string,arg3:string):Promise<Array<main.dataToShow>>;

export function GetProgramCode(arg1:string):Promise<string>;

export function GetProgramTitles():Promise<Array<string>>;

export function GetStateCode(arg1:string):Promise<string>;

export function GetStateNameToCode():Promise<{[key: string]: string}>;

export function GetStateNames():Promise<Array<string>>;

export function LoadProgramData():Promise<void>;

export function LoadStateData():Promise<void>;

export function SearchProgramTitles(arg1:string):Promise<Array<string>>;
