// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetData'](arg1, arg2, arg3);
}

export function GetProgramCode(arg1) {
  return window['go']['main']['App']['GetProgramCode'](arg1);
}

export function GetProgramTitles() {
  return window['go']['main']['App']['GetProgramTitles']();
}

export function GetStateCode(arg1) {
  return window['go']['main']['App']['GetStateCode'](arg1);
}

export function GetStateNameToCode() {
  return window['go']['main']['App']['GetStateNameToCode']();
}

export function GetStateNames() {
  return window['go']['main']['App']['GetStateNames']();
}

export function LoadProgramData() {
  return window['go']['main']['App']['LoadProgramData']();
}

export function LoadStateData() {
  return window['go']['main']['App']['LoadStateData']();
}

export function SearchProgramTitles(arg1) {
  return window['go']['main']['App']['SearchProgramTitles'](arg1);
}
