// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SubmitAnswer(arg1:Array<main.TestItem>):Promise<Array<boolean>>;

export function TestOne():Promise<Array<main.TestItem>>;

export function TestTwo():Promise<Array<main.TestItem>>;
