// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SubmitAnswer(arg1) {
  return window['go']['main']['App']['SubmitAnswer'](arg1);
}

export function TestOne() {
  return window['go']['main']['App']['TestOne']();
}

export function TestTwo() {
  return window['go']['main']['App']['TestTwo']();
}
