// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string):Promise<boolean>;

export function Query(arg1:main.QueryType,arg2:string):Promise<Array<main.Country>>;
