// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectBreed():Promise<Array<string>>;

export function FetchAnyBreed():Promise<any>;

export function FetchByBreed(arg1:string):Promise<Array<string>>;
