// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupDb():void;

export function CreateRef(arg1:main.Reference):void;

export function Delete(arg1:string):Promise<boolean>;

export function DeleteCustom(arg1:string):Promise<number>;

export function GetBookTitles():Promise<Array<string>>;

export function GetCategories():Promise<Array<string>>;

export function GetIds():Promise<Array<string>>;

export function GetIsbns():Promise<Array<string>>;

export function GetKeywords():Promise<Array<string>>;

export function GetUrls():Promise<Array<string>>;

export function OpenCustomStmtFile():Promise<Array<string>>;

export function QueryAll():Promise<Array<main.Reference>>;

export function QueryByBookTitle(arg1:string):Promise<Array<main.Reference>>;

export function QueryByCategory(arg1:string):Promise<Array<main.Reference>>;

export function QueryByDate(arg1:string,arg2:string):Promise<Array<main.Reference>>;

export function QueryById(arg1:string):Promise<main.Reference>;

export function QueryByIsbn(arg1:string):Promise<Array<main.Reference>>;

export function QueryByKeywords(arg1:string):Promise<Array<main.Reference>>;

export function QueryByUrl(arg1:string):Promise<Array<main.Reference>>;

export function QueryCustom(arg1:string):Promise<Array<main.Reference>>;

export function Update(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function UpdateCustom(arg1:string):Promise<number>;
