// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDb() {
  return window['go']['main']['App']['BackupDb']();
}

export function CreateRef(arg1) {
  return window['go']['main']['App']['CreateRef'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function DeleteCustom(arg1) {
  return window['go']['main']['App']['DeleteCustom'](arg1);
}

export function GetBookTitles() {
  return window['go']['main']['App']['GetBookTitles']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetIds() {
  return window['go']['main']['App']['GetIds']();
}

export function GetIsbns() {
  return window['go']['main']['App']['GetIsbns']();
}

export function GetKeywords() {
  return window['go']['main']['App']['GetKeywords']();
}

export function GetUrls() {
  return window['go']['main']['App']['GetUrls']();
}

export function OpenCustomStmtFile() {
  return window['go']['main']['App']['OpenCustomStmtFile']();
}

export function QueryAll() {
  return window['go']['main']['App']['QueryAll']();
}

export function QueryByBookTitle(arg1) {
  return window['go']['main']['App']['QueryByBookTitle'](arg1);
}

export function QueryByCategory(arg1) {
  return window['go']['main']['App']['QueryByCategory'](arg1);
}

export function QueryByDate(arg1, arg2) {
  return window['go']['main']['App']['QueryByDate'](arg1, arg2);
}

export function QueryById(arg1) {
  return window['go']['main']['App']['QueryById'](arg1);
}

export function QueryByIsbn(arg1) {
  return window['go']['main']['App']['QueryByIsbn'](arg1);
}

export function QueryByKeywords(arg1) {
  return window['go']['main']['App']['QueryByKeywords'](arg1);
}

export function QueryByUrl(arg1) {
  return window['go']['main']['App']['QueryByUrl'](arg1);
}

export function QueryCustom(arg1) {
  return window['go']['main']['App']['QueryCustom'](arg1);
}

export function Update(arg1, arg2, arg3) {
  return window['go']['main']['App']['Update'](arg1, arg2, arg3);
}

export function UpdateCustom(arg1) {
  return window['go']['main']['App']['UpdateCustom'](arg1);
}
