// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SearchDocuments(arg1:main.QueryParams,arg2:string):Promise<Array<main.Doc>>;
